GET http://localhost:3000/api/articles
Accept: application/json

###
GET http://localhost:3000/api/articles/6vmzaH
Accept: application/json

###
GET http://localhost:3000/api/categories
Accept: application/json

###
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "Заголовок. Обязательное поле. Минимум 30 символов.",
  "createdDate": "2021-01-01T14:17:04.305Z",
  "announce": "Анонс публикации. Обязательное поле. Минимум 30 символов. Максимум 250",
  "category": ["Программирование", "ssd"],
  "fullText": "Полный текст публикации. Необязательное поле. Максимум 1000 символов"
}

###
PUT http://localhost:3000/api/articles/6vmzaH
Content-Type: application/json

{
  "title": "Заголовок. Обязательное поле. Минимум 30 символов. Updated",
  "createdDate": "2021-01-01T14:27:04.305Z",
  "announce": "Анонс публикации. Обязательное поле. Updated article content",
  "category": "Программирование"
}

###
DELETE http://localhost:3000/api/articles/kMF_UH
Accept: application/json

###
GET http://localhost:3000/api/articles/6vmzaH/comments
Accept: application/json

###
DELETE http://localhost:3000/api/articles/6vmzaH/comments/yUg25J
Accept: application/json

###
POST http://localhost:3000/api/articles/6vmzaH/comments/
Content-Type: application/json

{
  "text": "Тестовый комментарий"
}

###
GET http://localhost:3000/api/search?query=альбом
Accept: application/json
