GET http://localhost:8080

###
GET http://localhost:8080/register

###
GET http://localhost:8080/login

###
GET http://localhost:8080/my

###
GET http://localhost:8080/my/comments

###
GET http://localhost:8080/articles/category/2

###
GET http://localhost:8080/articles/add

###
GET http://localhost:8080/search

###
GET http://localhost:8080/articles/edit/2

###
GET http://localhost:8080/articles/2

###
GET http://localhost:8080/categories
